"""empty message

Revision ID: 1524cd46271c
Revises: 
Create Date: 2024-05-12 14:00:06.889973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1524cd46271c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
