"""empty message

Revision ID: 97f9c5a5c070
Revises: 2a0aa4272018
Create Date: 2024-05-19 18:29:29.211129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97f9c5a5c070'
down_revision = '2a0aa4272018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('topics', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('subjectgrade', schema=None) as batch_op:
        batch_op.alter_column('achieved_grade',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjectgrade', schema=None) as batch_op:
        batch_op.alter_column('achieved_grade',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('topics')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
