"""empty message

Revision ID: b3eae458bba3
Revises: 97f9c5a5c070
Create Date: 2024-06-15 09:33:41.842195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3eae458bba3'
down_revision = '97f9c5a5c070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('advisor_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('subjectgrade', schema=None) as batch_op:
        batch_op.alter_column('achieved_grade',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjectgrade', schema=None) as batch_op:
        batch_op.alter_column('achieved_grade',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('advisor_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
