from app.models.admin import Admin
from app.models.program import Program
from app.models.advisor import Advisor
from app.models.student import Student
from app.models.semester import Semester
from app.models.subject import Subject
from app.models.assessment import Assessment
from app.models.grade import Grade
from app.models.subject_grade import SubjectGrade